import { Button, Text, View, Image, StyleSheet, ScrollView} from 'react-native';
import React, { Component } from 'react';
import { PFText , PFCard, PFActiveOrders, PFFlatList } from '../../../components';

export default function TermsAndConditions({navigation}) {
  return (
  


    <View style = {{margin: 15}}>
      <ScrollView>
    <PFText>Updated at 2022-05-09</PFText>
    <PFText>General Terms</PFText>
    <PFText>
    By accessing and placing an order with, you confirm that you are in agreement with and bound by the terms of service 
    contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other 
    type of communication between you and.
    </PFText>
    <PFText>
    By accessing and placing an order with, you confirm that you are in agreement with and bound by the terms of service 
    contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other 
    type of communication between you and.
    </PFText>
    <PFText>
    Under no circumstances shall team be liable for any direct, indirect, special, incidental or consequential damages, 
    including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials 
    on this site, even if team or an authorized representative has been advised of the possibility of such damages.
     If your use of materials from this site results in the need for servicing, repair or correction of equipment or 
     data, you assume any costs thereof. will not be responsible for any outcome that may occur during the course of 
     usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.
    </PFText>
    <PFText>License</PFText>
    <PFText>
    Phytoflex grants you a revocable, non-exclusive, non- transferable, limited license to download, install and use our 
    service strictly in accordance with the terms of this Agreement.
    </PFText>
    <PFText>
    These Terms & Conditions are a contract between you and Phytoflex (referred to in these Terms & Conditions as 
    "Phytoflex", "us", "we" or "our"), the provider of the Phytoflex website and the services accessible from the
     Phytoflex website (which are collectively referred to in these Terms & Conditions as the "Phytoflex Service").
    You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please
     do not use the Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity 
     you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block 
     access to your account without notice.
    </PFText>
    <PFText>Definitions and key terms</PFText>
    <PFText>For this Terms & Conditions:</PFText>
    <PFText>•Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify 
    your browser, provide analytics, remember information about you such as your language preference or login information.</PFText>
    <PFText>•Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Flex Inc., 370 Regalado Hwy, 
    Novaliches, Quezon City, Metro Manila 1118 that is responsible for your information under this Privacy Policy.</PFText>
    <PFText>•Country: where Phytoflex or the owners/founders of Phytoflex are based, in this case is Philippines.</PFText>
    <PFText>
    •Customer: refers to the company, organization or person that signs up to use the Phytoflex Service to manage 
    the relationships with your consumers or service users.
    </PFText>
  
  
  </ScrollView>
  </View>

  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10
  },
});